config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: 'members'
  resources :form_barats 
  
  root :to => "pages#index"

  get 'wilayah_barat' => 'wilayah_barats#index'
  get 'wilayah_barat/aceh' => 'wilayah_barats#aceh'
  get 'wilayah_barat/sumaterautara' => 'wilayah_barats#sumatera_utara'
  get 'wilayah_barat/riau' => 'wilayah_barats#riau'
  get 'wilayah_barat/kepulauanriau' => 'wilayah_barats#kepulauan_riau'
  get 'wilayah_barat/sumaterabarat' => 'wilayah_barats#sumatera_barat'
  get 'wilayah_barat/bengkulu' => 'wilayah_barats#bengkulu'
  get 'wilayah_barat/sumateraselatan' => 'wilayah_barats#sumatera_selatan'
  get 'wilayah_barat/lampung' => 'wilayah_barats#lampung'
  get 'wilayah_barat/banten' => 'wilayah_barats#banten'
  get 'wilayah_barat/jawatimur' => 'wilayah_barats#jawa_timur'

  get 'wilayah_barat/mydata' => 'form_barats#barat_mydata'



  resources :members do
    resources :form_barats
  end
end

app/models/form_barat.rb
class FormBarat < ActiveRecord::Base
  
	belongs_to :members

	before_save do
		self.sumber_listrik.gsub!(/[\[\]\"]/,"") if attribute_present?("sumber_listrik")
	end
  
  before_save do
    self.transportasi_menuju_lokasi.gsub!(/[\[\]\"]/,"") if attribute_present?("transportasi_menuju_lokasi")
  end

    before_save do
    self.jenis_koneksi.gsub!(/[\[\]\"]/,"") if attribute_present?("jenis_koneksi")
  end

  before_save do
    self.jenis_koneksi_1.gsub!(/[\[\]\"]/,"") if attribute_present?("jenis_koneksi_1")
  end

	  has_attached_file :image_gedung
  	validates_attachment_content_type :image_gedung, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_rencana_tempat_perangkat
  	validates_attachment_content_type :image_rencana_tempat_perangkat, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_genset
  	validates_attachment_content_type :image_genset, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_lingkungan_depan
  	validates_attachment_content_type :image_lingkungan_depan, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_lingkungan_belakang
  	validates_attachment_content_type :image_lingkungan_belakang, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_lingkungan_kiri
  	validates_attachment_content_type :image_lingkungan_kiri, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_lingkungan_kanan
  	validates_attachment_content_type :image_lingkungan_kanan, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_akses_ke_site
  	validates_attachment_content_type :image_akses_ke_site, content_type: /\Aimage\/.*\z/

  	has_attached_file :image_akses_ke_site_1
  	validates_attachment_content_type :image_akses_ke_site_1, content_type: /\Aimage\/.*\z/

    has_attached_file :photo_sketsa
    validates_attachment_content_type :photo_sketsa, content_type: /\Aimage\/.*\z/

    has_attached_file :image_geotagging
    validates_attachment_content_type :image_geotagging, content_type: /\Aimage\/.*\z/

    has_attached_file :image_surveyor
    validates_attachment_content_type :image_surveyor, content_type: /\Aimage\/.*\z/

    has_attached_file :image_tambahan_photo_1
    validates_attachment_content_type :image_tambahan_photo_1, content_type: /\Aimage\/.*\z/


    validates_presence_of :alamat, :kelurahan, :kecamatan, :kabupaten, :provinsi, :lattide, :longitude, :jumlah_komputer, :nama_penanggung_jawab_lokasi_1, :kontak_penanggung_jawab_lokasi_1, :nama_penanggung_jawab_lokasi_2, :kontak_penanggung_jawab_lokasi_2, :catatan_tambahan,:gambaran_menuju_lokasi, :surveyor, :project, :keterangan_menuju_lokasi, :transportasi_menuju_lokasi, :message => "Tidak Boleh Kosong" 

    def self.search(search)
      where("lower(kabupaten) LIKE ? OR lower(provinsi) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%") 
    end

    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |survey_form|
          csv << survey_form.attributes.values_at(*column_names)
        end
      end
    end

end

app/controllers/form_barats_controller.rb
class FormBaratsController < ApplicationController
  before_action :set_form_barat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_member!, :except => [:index, :show]
  before_action :job_owner, only: [:edit, :update, :destroy]


  # GET /form_barats
  # GET /form_barats.json
  def index
    @form_barats = FormBarat.all
    if params[:search]
      @form_barats = FormBarat.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(20)
    else
      @form_barats = FormBarat.all.order('created_at DESC').page(params[:page]).per_page(20)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @form_barats.to_csv }
      format.xls { send_data @form_barats.to_csv(col_sep: "\t") }
    end
  end

  

  # GET /form_barats/1
  # GET /form_barats/1.json
  def show
  end

  # GET /form_barats/new
  def new
    @form_barat = FormBarat.new
  end

  # GET /form_barats/1/edit
  def edit
  @form_barat = FormBarat.find(params[:id])
  @member = current_member
  form_barats = current_member.form_barats
  @members = @member.form_barats
  end

  def job_owner
     unless @form_barat.member_id == current_member.id
      flash[:notice] = 'Access denied as you are not owner of this Job'
      redirect_to wilayah_barat_mydata_path
     end
    end

  def barat_mydata
    @member = current_member
    form_barats = current_member.form_barats
    @members = @member.form_barats
    #@form_barats = FormBarat.all
  end

  # POST /form_barats
  # POST /form_barats.json
  def create
    #@form_barat = FormBarat.new(form_barat_params)
    @form_barat = current_member.form_barats.create(form_barat_params)


    respond_to do |format|
      if @form_barat.save
        format.html { redirect_to form_barats_path, notice: 'Form barat was successfully created.' }
        format.json { render :show, status: :created, location: @form_barat }
      else
        format.html { render :new }
        format.json { render json: @form_barat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_barats/1
  # PATCH/PUT /form_barats/1.json
  def update
    respond_to do |format|
      if @form_barat.update(form_barat_params)
        format.html { redirect_to form_barats_path, notice: 'Form barat was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_barat }
      else
        format.html { render :edit }
        format.json { render json: @form_barat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_barats/1
  # DELETE /form_barats/1.json
  def destroy
    @form_barat.destroy
    respond_to do |format|
      format.html { redirect_to form_barats_url, notice: 'Form barat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_barat
      @form_barat = FormBarat.find(params[:id])
    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def form_barat_params
      params.require(:form_barat).permit(:side_id, :nama_site_id,:alamat, :kelurahan, :kecamatan, :kabupaten, :provinsi, :lattide, :longitude, :jam_operasional, :id_pelanggan_listrik, :kapasitas, :lainnya_internet, :bandwidt_tersedia, :nama_operator_seluler, :kualitas_layanan, :jumlah_komputer, :perangkat_pendukung_lainnya, :nama_penanggung_jawab_lokasi_1, :kontak_penanggung_jawab_lokasi_1, :nama_penanggung_jawab_lokasi_2, :kontak_penanggung_jawab_lokasi_2, :keterangan_menuju_lokasi, :catatan_tambahan, :gambaran_menuju_lokasi, :surveyor, :project, :perangkat_lainnya,:kualitas_akses_internet, :photo_sketsa, :image_gedung, :image_rencana_tempat_perangkat, :image_genset, :image_lingkungan_depan, :image_lingkungan_belakang, :image_lingkungan_kiri, :image_lingkungan_kanan, :image_akses_ke_site, :image_akses_ke_site_1, :image_geotagging, :image_surveyor,:image_tambahan_photo_1,jenis_koneksi_1:[], sumber_listrik:[], jenis_koneksi:[], transportasi_menuju_lokasi:[])
    end
end

app/helpers/form_barats_helper.rb
module FormBaratsHelper

	def checked4(area)
		@form_barat.sumber_listrik.nil? ? false : @form_barat.sumber_listrik.match(area)
	end

	def checked5(area)
		@form_barat.jenis_koneksi.nil? ? false : @form_barat.jenis_koneksi.match(area)
	end

	def checked6(area)
		@form_barat.jenis_koneksi_1.nil? ? false : @form_barat.jenis_koneksi_1.match(area)
	end

	def checked7(area)
		@form_barat.transportasi_menuju_lokasi.nil? ? false : @form_barat.transportasi_menuju_lokasi.match(area)
	end



end

app/views/form_barats/barat_mydata.html.erb
<div class="container-fluid">
<div class="table-responsive">
<table class="table table-stripted table-hover table-responsive">
  <thead>
    <tr>
            
            <th>Provinsi</th>
            <th>Kota / Kabupaten</th>
            <th>Action</th>
      
    </tr>
  </thead>  
  <tbody>     
       <% @members.each do |member| %>
            <tr>
              <td data-title="Provinsi"><%= member.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= member.kabupaten %></td>
              <td><%= link_to 'Show', member %>
              <%= link_to 'Edit', edit_form_barat_path(member) %>
              <%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
            </tr>
    <% end %>
      </tbody>
</table>
</div>
</div>

app/views/form_barats/edit.html.erb
<h1><center>Editing Form Barat</center></h1>

<%= render 'form' %>

<%= link_to 'Show', @form_barat %> |
<%= link_to 'Back', form_barats_path %>

app/views/form_barats/index.html.erb
  <style>
    body {
      background-color: #ffe6e6;
    }
    @media print {
    .no_print { 
        display: none; 
    }
}
  </style>

<p id="notice"><%= notice %></p>

<center><h1>Data Survey Wilayah Barat</h1></center>
<br />
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag form_barats_path, class: "no_print", :method => 'get' do %>
      <select class="selectpicker form-control" data-show-subtext="true" data-live-search="true" name="search" id="search">
              <option disabled selected>Select Provinsi</option>
              <option>Aceh</option>
              <option>Banten</option>
              <option>Bengkulu</option>
              <option>Jawa Timur</option>
              <option>Kepulauan Riau</option>
              <option>Lampung</option>
              <option>Riau</option>
              <option>Sumatera Barat</option>
              <option>Sumatera Utara</option>
              <option>Sumatera Selatan</option>
      </select>
      <br /><br />
      <center><%= submit_tag "Search", class: "btn btn-success"%></center>
    <% end %>
  </div>
  <br /><br />
 
<div class="container-fluid">
<div class="col-md-12">

<% if current_member %>
  <p class="no_print">
    Download Data:<br />
    <button class="btn btn-sm btn-danger" onclick="myFunction()">Print PDF</button>
  </p>
<% end %>

  <div class="table-responsive">
    <table class="table" width="100%">
        <% @form_barats.each do |form_barat| %>
          <tr>
            <th width="50%">Site ID</th>
            <td width="50%"><%= form_barat.side_id %></td>
          </tr>
          <tr>
            <th>Nama Site</th>
            <td><%= form_barat.nama_site_id %></td>
          </tr>
          <tr>
            <th>Alamat</th>
            <td><%= form_barat.alamat %></td>
          </tr>
          <tr>
            <th>Provinsi</th>
            <td><%= form_barat.provinsi %></td>
          </tr>
          <tr>
            <th>Kabupaten</th>
            <td><%= form_barat.kabupaten %></td>
          </tr>
          <tr>
            <th>Kecamatan</th>
            <td><%= form_barat.kecamatan %></td>
          </tr>
          <tr>
            <th>Kelurahan</th>
            <td><%= form_barat.kelurahan %></td>
          </tr>
          
          <tr>
            <th>Surveyor</th>
            <td><%= form_barat.surveyor %></td>
          </tr>
          <tr>
            <th>Project</th>
            <td><%= form_barat.project %></td>
          </tr>
          <tr>
            <th>Lattide</th>
            <td><%= form_barat.lattide %></td>
          </tr>
          <tr>
            <th>Longitude</th>
            <td><%= form_barat.longitude %></td>
          </tr>
          <tr>
            <th>Sumber listrik</th>
            <td><%= form_barat.sumber_listrik %></td>
          </tr>
          <tr>
            <th>Jam operasional</th>
            <td><%= form_barat.jam_operasional %></td>
          </tr>
          <tr>
            <th>Id pelanggan listrik</th>
            <td><%= form_barat.id_pelanggan_listrik %></td>
          </tr>
          <tr>
            <th>Kapasitas</th>
            <td><%= form_barat.kapasitas %></td>
          </tr>
          <tr>
            <th>Jenis Koneksi Internet Eksisting</th>
            <td><%= form_barat.jenis_koneksi %></td>
          </tr>
          <tr>
            <th>Koneksi Internet Lainnya</th>
            <td><%= form_barat.lainnya_internet %></td>
          </tr>
          <tr>
            <th>Kualitas akses internet</th>
            <td><%= form_barat.kualitas_akses_internet %></td>
          </tr>
          <tr>
            <th>Bandwidt tersedia</th>
            <td><%= form_barat.bandwidt_tersedia %></td>
          </tr>
          <tr>
            <th>Jenis Koneksi Seluler</th>
            <td><%= form_barat.jenis_koneksi_1 %></td>
          </tr>
          <tr>
            <th>Nama operator seluler</th>
            <td><%= form_barat.nama_operator_seluler %></td>
          </tr>
          <tr>
            <th>Kualitas layanan</th>
            <td><%= form_barat.kualitas_layanan %></td>
          </tr>
          <tr>
            <th>Jumlah komputer</th>
            <td><%= form_barat.jumlah_komputer %></td>
          </tr>
          <tr>
            <th>Perangkat pendukung</th>
            <td><%= form_barat.perangkat_pendukung_lainnya %></td>
          </tr>
          <tr>
            <th>Lainnya</th>
            <td><%= form_barat.perangkat_lainnya %></td>
          </tr>
          <tr>
            <th>Nama penanggung jawab lokasi 1</th>
            <td><%= form_barat.nama_penanggung_jawab_lokasi_1 %></td>
          </tr>
          <tr>
            <th>Kontak penanggung jawab lokasi 1</th>
            <td><%= form_barat.kontak_penanggung_jawab_lokasi_1 %></td>
          </tr>
          <tr>
            <th>Nama penanggung jawab lokasi 2</th>
            <td><%= form_barat.nama_penanggung_jawab_lokasi_2 %></td>
          </tr>
          <tr>
            <th>Kontak penanggung jawab lokasi 2</th>
            <td><%= form_barat.kontak_penanggung_jawab_lokasi_2 %></td>
          </tr>
          <tr>
            <th>Transportasi menuju lokasi</th>
            <td><%= form_barat.transportasi_menuju_lokasi %></td>
          </tr>
          <tr>
          <tr>
            <th>Keterangan Menuju Lokasi</th>
            <td><%= form_barat.keterangan_menuju_lokasi %></td>
          </tr>
          <tr>
            <th>Gambaran menuju lokasi</th>
            <td><%= form_barat.gambaran_menuju_lokasi %></td>
          </tr>
          <tr>
            <th>Catatan Tambahan</th>
            <td><%= form_barat.catatan_tambahan %></td>
          </tr>
          <tr class="no_print">
            <th>Photo</th>
            <td><%= link_to 'Data Photo', form_barat, class: "btn btn-sm btn-success" %></td>
          </tr> 
          <tr>
            <th colspan="2"></th>
          </tr>     
        <% end %>
    </table>
  </div>
</div>
</div>

<script>
function myFunction() {
    window.print();
}
</script>

<script type="text/javascript">
$('select').select2({width: "100%"});
</script>

app/views/form_barats/new.html.erb
<%= render 'layouts/navbar' %>
  <div class="container">
  <%= render 'form' %>
</div>

app/views/form_barats/show.html.erb
 
 <style>
  body {
      background-color: #ccffff;
  }

  img {
    cursor: zoom-in;
}
@media print {
    .no_print { 
        display: none; 
    }
  </style>

<p id="notice"><%= notice %></p>

<center><h1>Data Photo</h1></center>

<div class="container-fluid">

  <div class="col-md-12">
  <% if current_member %>
  <p class="no_print">Download Data:<br />
    <button class="btn btn-sm btn-danger" onclick="myFunction()">Print PDF</button>
  </p>
  <% end %>
    <br/>
    <div class="table-responsive">
      <table class="table" width="100%">
        
        <tr>
            <th width="50%">Site ID</th>
            <td width="50%"><%= @form_barat.side_id %></td>
          </tr>
          <tr>
            <th>Nama Site</th>
            <td><%= @form_barat.nama_site_id %></td>
          </tr>
        <tr>
          <th >Provinsi:</th>
          <td  width="50%"><%= @form_barat.provinsi %></td>
        </tr>
        <tr>
          <th  width="50%">Kecamatan:</th>
          <td  width="50%"><%= @form_barat.kecamatan %></td>
        </tr>
        <tr>
          <th  width="50%">Kelurahan:</th>
          <td  width="50%"><%= @form_barat.kelurahan %></td>
        </tr>
        <tr>
          <th>Photo Sketsa/Layout</th>
          <td><a href="#"><%= image_tag @form_barat.photo_sketsa.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Gedung</th>
          <td><a href="#"><%= image_tag @form_barat.image_gedung.url, style: "width:35%;",class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Rencana Tempat Perangkat</th>
          <td><a href="#"><%= image_tag @form_barat.image_rencana_tempat_perangkat.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Depan</th>
          <td><a href="#"><%= image_tag @form_barat.image_lingkungan_depan.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Belakang</th>
          <td><a href="#"><%= image_tag @form_barat.image_lingkungan_belakang.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Kiri</th>
          <td><a href="#"><%= image_tag @form_barat.image_lingkungan_kiri.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Lingkungan Kanan</th>
          <td><a href="#"><%= image_tag @form_barat.image_lingkungan_kanan.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Akses ke Site 1</th>
          <td><a href="#"><%= image_tag @form_barat.image_akses_ke_site.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Akses ke Site 2</th>
          <td><a href="#"><%= image_tag @form_barat.image_akses_ke_site_1.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>

        <tr>
          <th>Photo Geotagging</th>
          <td><a href="#"><%= image_tag @form_barat.image_geotagging.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Surveyor</th>
          <td><a href="#"><%= image_tag @form_barat.image_surveyor.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>
        <tr>
          <th>Photo Tambahan 1</th>
          <td><a href="#"><%= image_tag @form_barat.image_tambahan_photo_1.url, style: "width:35%;", class:"img-responsive" %></a></td>
        </tr>

         <div class="modal fade" id="enlargeImageModal" tabindex="-1" role="dialog" aria-labelledby="enlargeImageModal" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                  <img src="" class="enlargeImageModalSource" style="width: 100%">
                </div>
              </div>
            </div>
          </div>

      </table>
    </div>
  </div>
</div>
<br>
<script>
  $(function() {
        $('img').on('click', function() {
        $('.enlargeImageModalSource').attr('src', $(this).attr('src'));
        $('#enlargeImageModal').modal('show');
      });
  });
</script>

<script>
function myFunction() {
    window.print();
}
</script>