config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: 'members'
  resources :form_barats 
  
  root :to => "pages#index"

  get 'wilayah_barat' => 'wilayah_barats#index'
  get 'wilayah_barat/aceh' => 'wilayah_barats#aceh'
  get 'wilayah_barat/sumaterautara' => 'wilayah_barats#sumatera_utara'
  get 'wilayah_barat/riau' => 'wilayah_barats#riau'
  get 'wilayah_barat/kepulauanriau' => 'wilayah_barats#kepulauan_riau'
  get 'wilayah_barat/sumaterabarat' => 'wilayah_barats#sumatera_barat'
  get 'wilayah_barat/bengkulu' => 'wilayah_barats#bengkulu'
  get 'wilayah_barat/sumateraselatan' => 'wilayah_barats#sumatera_selatan'
  get 'wilayah_barat/lampung' => 'wilayah_barats#lampung'
  get 'wilayah_barat/banten' => 'wilayah_barats#banten'
  get 'wilayah_barat/jawatimur' => 'wilayah_barats#jawa_timur'

  get 'wilayah_barat/mydata' => 'form_barats#barat_mydata'



  resources :members do
    resources :form_barats
  end
end

app/controllers/wilayah_barats_controller.rb
class WilayahBaratsController < ApplicationController
  before_action :set_wilayah_barat, only: [:show, :edit, :update, :destroy]

  # GET /wilayah_barats
  # GET /wilayah_barats.json
  def index
    #@form_barats = FormBarat.all.where(provinsi:"Aceh")
    @form_barats = FormBarat.all
  end

  def aceh
    #@form_barats = FormBarat.all
    @form_barats = FormBarat.all.where(provinsi:"Aceh")
  end

  def sumatera_utara
    @form_barats = FormBarat.all.where(provinsi:"Sumatera Utara")
  end

  def riau
    @form_barats = FormBarat.all.where(provinsi:"Riau")
  end

  def kepulauan_riau
    @form_barats = FormBarat.all.where(provinsi:"Kepulauan Riau")
  end

  def sumatera_barat
    @form_barats = FormBarat.all.where(provinsi:"Sumatera_Barat")
  end

  def bengkulu
    @form_barats = FormBarat.all.where(provinsi:"Bengkulu")
  end

  def sumatera_selatan
    @form_barats = FormBarat.all.where(provinsi:"Sumatera Selatan")
  end

  def lampung
   @form_barats = FormBarat.all.where(provinsi:"Lampung")
  end

  def banten
    @form_barats = FormBarat.all.where(provinsi:"Banten")
  end
  
  def jawa_timur
    @form_barats = FormBarat.all.where(provinsi:"Jawa Timur")
  end
end

app/helpers/wilayah_barats_helper.rb
module WilayahBaratsHelper
end

app/views/wilayah_barats/aceh.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Aceh</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= pie_chart FormBarat.where(provinsi:"Aceh").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>     

<!--
 <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Aceh Per Kecamatan</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%#= pie_chart FormBarat.where(provinsi:"Aceh").group(:kecamatan).count, discrete: true, donut:true %>
                </div>
              </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Aceh Per Kelurahan</strong></h5>  
            </div>
            <div class="panel-body">
              <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <%#= pie_chart FormBarat.where(provinsi:"Aceh").group(:kelurahan).count, discrete: true, donut:true %>
              </div>
            </div>
          </div>  
        </div>
  </div>
-->

<div class="container">
  <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
          </tr>
        </thead>

        <tbody>
          <% @form_barats.each do |form_barat| %>
            <tr>
              <td data-title="Provinsi"><%= form_barat.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kabupaten %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kecamatan %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kelurahan %></td>
              <td data-title="Kecamatan"><%= form_barat.lattide %></td>
              <td data-title="Kelurahan"><%= form_barat.longitude %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>       
  </div>   

app/views/wilayah_barats/banten.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Banten</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart FormBarat.where(provinsi:"Banten").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div> 

  
 <!--<div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Banten Per Kecamatan</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%#= pie_chart FormBarat.where(provinsi:"Banten").group(:kecamatan).count, discrete: true, donut:true %>
                </div>
              </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Banten Per Kelurahan</strong></h5>  
            </div>
            <div class="panel-body">
              <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <%#= pie_chart FormBarat.where(provinsi:"Banten").group(:kelurahan).count, discrete: true, donut:true %>
              </div>
            </div>
          </div>  
        </div>
  </div>
  --> 

  <div class="container">
  <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
          </tr>
        </thead>

        <tbody>
          <% @form_barats.each do |form_barat| %>
            <tr>
              <td data-title="Provinsi"><%= form_barat.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kabupaten %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kecamatan %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kelurahan %></td>
              <td data-title="Kecamatan"><%= form_barat.lattide %></td>
              <td data-title="Kelurahan"><%= form_barat.longitude %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>  
</div>   

app/views/wilayah_barats/bengkulu.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Bengkulu</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart FormBarat.where(provinsi:"Bengkulu").group(:kabupaten).count, discrete: true,donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>  

<!--
 <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Bengkulu Per Kecamatan</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%#= pie_chart FormBarat.where(provinsi:"Bengkulu").group(:kecamatan).count, discrete: true, donut:true, messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Bengkulu Per Kelurahan</strong></h5>  
            </div>
            <div class="panel-body">
              <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <%#= pie_chart FormBarat.where(provinsi:"Bengkulu").group(:kelurahan).count, discrete: true, donut:true, messages: {empty: "No data"} %>
              </div>
            </div>
          </div>  
        </div>
  </div>
  --> 

 <div class="container">
  <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
          </tr>
        </thead>

        <tbody>
          <% @form_barats.each do |form_barat| %>
            <tr>
              <td data-title="Provinsi"><%= form_barat.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kabupaten %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kecamatan %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kelurahan %></td>
              <td data-title="Kecamatan"><%= form_barat.lattide %></td>
              <td data-title="Kelurahan"><%= form_barat.longitude %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>   
  </div>   

app/views/wilayah_barats/index.html.erb
<style type="text/css">
</style>
<div class="container-fluid">
<center><h3>Data Survey Wilayah Barat Yang Sudah Masuk</h3></center><hr>  
<hr>
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-4 col-md-4">
                <div class="table-responsive">
                  <table class="table-responsive" style="width:100%; color: #000">
                        <tr>
                          <th style="width:10%; text-align: center;">NO</th>
                          <th style="width:40%;text-align: center;">Provinsi</th>
                          <th style="width:25%;text-align: center;">Target Data Masuk</th>
                          <th style="width:25%;text-align: center;">Jumlah Data Masuk</th> 
                        </tr>
                        <tr>
                          <td style="text-align: center;">1</td>
                          <td><%= link_to "Aceh", wilayah_barat_aceh_path %></td>
                          <td style="text-align: center;">31</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Aceh").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">2</td>
                          <td><%= link_to "Banten", wilayah_barat_banten_path %></td>
                          <td style="text-align: center;">54</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Banten").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">3</td>
                          <td><%= link_to "Bengkulu", wilayah_barat_bengkulu_path %></td>
                          <td style="text-align: center;">27</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Bengkulu").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">4</td>
                          <td ><%= link_to "Jawa Timur", wilayah_barat_jawatimur_path %></td>
                          <td style="text-align: center;">2</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Jawa Timur").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">5</td>
                          <td><%= link_to "Kepulauan Riau", wilayah_barat_kepulauanriau_path%></td>
                          <td style="text-align: center;">43</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Kepulauan Riau").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">6</td>
                          <td><%= link_to "Lampung", wilayah_barat_lampung_path %></td>
                          <td style="text-align: center;">3</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Lampung").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">7</td>
                          <td><%= link_to "Riau", wilayah_barat_riau_path %></td>
                          <td style="text-align: center;">8</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Riau").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">8</td>
                          <td><%= link_to "Sumatera Barat", wilayah_barat_sumaterabarat_path %></td>
                          <td style="text-align: center;">27</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Sumatera Barat").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">9</td>
                          <td><%= link_to "Sumatera Selatan", wilayah_barat_sumateraselatan_path %></td>
                          <td style="text-align: center;">40</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Sumatera Selatan").count %></td>
                        </tr>
                        <tr>
                          <td style="text-align: center;">10</td>
                          <td><%= link_to "Sumatera Utara", wilayah_barat_sumaterautara_path %></td>
                          <td style="text-align: center;">35</td>
                          <td style="text-align: center;"><%= @form_barats.where(provinsi:"Sumatera Utara").count %></td>
                        </tr>
                  </table>
                </div>
                </div>
                <div class= "col-lg-7 col-md-7">
                    <%= pie_chart FormBarat.group(:provinsi).count, donut:true, messages: {empty: "No data"} %>
                </div>
             </div>
            </div>

  <div class="row">
    <div class="col-lg-12 col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat</strong></h5>  
            </div>
             <ul class="nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#home">Per-Hari</a></li>
                  <li><a data-toggle="tab" href="#menu1">Per-Minggu</a></li>
                  <li><a data-toggle="tab" href="#menu2">Per-Bulan</a></li>
                  <li><a data-toggle="tab" href="#menu3">Per-Tahun</a></li>
                </ul><br> 
            <div class="panel-body">
               <div class="tab-content">
                  <div id="home" class="tab-pane fade in active">
                         <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @form_barats.group_by_day(:created_at, format: "%d %B , %Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Hari", ytitle: "Jumlah Data Masuk" %>;

                              </div>
                        </div>
                  </div>
                  <div id="menu1" class="tab-pane fade">
                         <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @form_barats.group_by_week(:created_at, format: "%d %B, %Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Minggu", ytitle: "Jumlah Data Masuk" %>;

                              </div>
                        </div>
                  </div>
                  <div id="menu2" class="tab-pane fade">
                        <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @form_barats.group_by_month(:created_at, format: "%B %Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Bulan", ytitle: "Jumlah Data Masuk" %>;

                              </div>
                        </div>
                  </div>
                  <div id="menu3" class="tab-pane fade">
                        <div class= "col-md-12">
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <%#= line_chart SurveyForm.group_by_day(:created_at, format: "%a").count %>
                               <%= line_chart @form_barats.group_by_year(:created_at, format: "%Y").count, discrete: true, messages: {empty: "No data"}, xtitle: "Tahun", ytitle: "Jumlah Data Masuk" %>;
                              </div>
                        </div>
                  </div>
               </div>
            </div>
          </div>
        </div>
  </div>
        <!-- statics end -->
<br>
    <div class="container">
    <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan/th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
            <th style="text-align: center;">Tanggal Dibuat</th>
          </tr>
        </thead>

        <tbody>
          <% @form_barats.each do |form_barat| %>
            <tr>
              <td data-title="Provinsi"><%= form_barat.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kabupaten %></td>
              <td data-title="Kecamatan"><%= form_barat.kecamatan %></td>
              <td data-title="Kelurahan"><%= form_barat.kelurahan %></td>
              <td data-title="lattide"><%= form_barat.lattide %></td>
              <td data-title="longitude"><%= form_barat.longitude %></td>
              <td data-title="Tanggal Dibuat"><%= form_barat.created_at.strftime '%d-%m-%Y' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
</div>  
</div>    
          

app/views/wilayah_barats/jawa_timur.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Jawa Timur</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart FormBarat.where(provinsi:"Jawa Timur").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div>   

    
<!--
 <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Jawa Timur Per Kecamatan</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%#= pie_chart FormBarat.where(provinsi:"Jawa Timur").group(:kecamatan).count, discrete: true, donut:true %>
                </div>
              </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Jawa Timur Per Kelurahan</strong></h5>  
            </div>
            <div class="panel-body">
              <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <%#= pie_chart FormBarat.where(provinsi:"Jawa Timur").group(:kelurahan).count, discrete: true, donut:true %>
              </div>
            </div>
          </div>  
        </div>
  </div>
  -->
  <div class="container">
  <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
          </tr>
        </thead>

        <tbody>
          <% @form_barats.each do |form_barat| %>
            <tr>
              <td data-title="Provinsi"><%= form_barat.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kabupaten %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kecamatan %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kelurahan %></td>
              <td data-title="Kecamatan"><%= form_barat.lattide %></td>
              <td data-title="Kelurahan"><%= form_barat.longitude %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div> 
  </div>   

app/views/wilayah_barats/kepulauan_riau.html.erb
 <div class="container-fluid">
  <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Kepulauan Riau</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-1">
                <%= pie_chart FormBarat.where(provinsi:"Kepulauan Riau").group(:kabupaten).count, discrete: true, donut:true, height: "400px", messages: {empty: "No data"} %>
                </div>
              </div>
            </div>
        </div>
  </div> 

     
<!--
 <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Kepulauan Riau Per Kecamatan</strong></h5>
              </div>
              <div class="panel-body">
                <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%#= pie_chart FormBarat.where(provinsi:"Kepulauan Riau").group(:kecamatan).count, discrete: true, donut:true %>
                </div>
              </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h5><i class="fa fa-flag-o red"></i><strong>Pemetaan Internet Wilayah Barat Provinsi Kepulauan Riau Per Kelurahan</strong></h5>  
            </div>
            <div class="panel-body">
              <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <%#= pie_chart FormBarat.where(provinsi:"Kepulauan Riau").group(:kelurahan).count, discrete: true, donut:true%>
              </div>
            </div>
          </div>  
        </div>
  </div> 
  -->

    <div class="container">
  <div class="table-responsive">
    <div class="col-md-12">          
      <table class="table table-bordered table-striped table-hover table-mc-light-blue">
        <thead>
          <tr>
            <th style="text-align: center;">Provinsi</th>
            <th style="text-align: center;">Kota / Kabupaten</th>
            <th style="text-align: center;">Kecamatan</th>
            <th style="text-align: center;">Kelurahan</th>
            <th style="text-align: center;">Lattide</th>
            <th style="text-align: center;">Longitude</th>
          </tr>
        </thead>

        <tbody>
          <% @form_barats.each do |form_barat| %>
            <tr>
              <td data-title="Provinsi"><%= form_barat.provinsi %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kabupaten %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kecamatan %></td>
              <td data-title="Kota/Kabupaten"><%= form_barat.kelurahan %></td>
              <td data-title="Kecamatan"><%= form_barat.lattide %></td>
              <td data-title="Kelurahan"><%= form_barat.longitude %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div> 
  </div>   