config/routes.rb
Rails.application.routes.draw do

  devise_for :members, path: 'members'
  resources :form_barats 
  
  root :to => "pages#index"

  get 'wilayah_barat' => 'wilayah_barats#index'
  get 'wilayah_barat/aceh' => 'wilayah_barats#aceh'
  get 'wilayah_barat/sumaterautara' => 'wilayah_barats#sumatera_utara'
  get 'wilayah_barat/riau' => 'wilayah_barats#riau'
  get 'wilayah_barat/kepulauanriau' => 'wilayah_barats#kepulauan_riau'
  get 'wilayah_barat/sumaterabarat' => 'wilayah_barats#sumatera_barat'
  get 'wilayah_barat/bengkulu' => 'wilayah_barats#bengkulu'
  get 'wilayah_barat/sumateraselatan' => 'wilayah_barats#sumatera_selatan'
  get 'wilayah_barat/lampung' => 'wilayah_barats#lampung'
  get 'wilayah_barat/banten' => 'wilayah_barats#banten'
  get 'wilayah_barat/jawatimur' => 'wilayah_barats#jawa_timur'

  get 'wilayah_barat/mydata' => 'form_barats#barat_mydata'



  resources :members do
    resources :form_barats
  end
end

app/views/layouts/_footer.html.erb
<br /><br />
<footer>
<section>
      <div class="text-right">
        <div class="credits">
          <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
          -->
          <center><a>Made by  </a><a>Teamwork</a></center>
        </div>
      </div>
</section>
</footer>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "style" %>
<% provide(:title, 'Dashboard Kominfo') %>

<% if current_member %>
<div class="header">
      <div class="header-nav">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">        
          
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand"><%= link_to image_tag("https://s3.amazonaws.com/kominfo/logo2.svg",size:"100x47"),root_path %></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "Data Wilayah Barat", form_barats_path %></li>
            <li><span class="nav-itemButton"><%= link_to "Form Survey ",new_form_barat_path,class:"btn button-smaller" %></li></span>
              <% if current_member %>
            <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                        <li class="divider"></li>
                        <li><a><%= link_to "My Data", wilayah_barat_mydata_path %></a></li>
                        <li><a><%= link_to "Logout", destroy_member_session_path || destroy_user_barat_session_path, method: :delete %></a>
                        </li>
                    </ul>
           </li> 
                <% end %>
            </ul>
          </div><!-- /navbar-collapse -->
         </div>

        </nav>
  </div>
  </div>
<% else %>
<div class="header">
      <div class="header-nav">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">        
          
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand" href="/"><%= link_to image_tag("https://s3.amazonaws.com/kominfo/logo2.svg",size:"100x47"),root_path %></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right"> 
            <li><%= link_to "Data Wilayah Barat", form_barats_path %></li>           
            <li><span class="nav-itemButton"><%= link_to "Login ",new_member_session_path,class:"btn button-smaller" %></li></span>          
              </li>
          </ul>
          </div><!-- /navbar-collapse -->
         </div>

        </nav>
  </div>
  </div>
  <% end %>
  <br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  <title>SurveyKominfo</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag  'application','data-turbolinks-track'=> true %>
      <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

    <%= favicon_link_tag 'kominfo.jpg' %>
	  <%= csrf_meta_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCGKsOuXHyfqzIz9Mix3gUWgBX_SYrJ3Sg"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


</head>
<body>
    <div class="mdk-drawer-layout js-mdk-drawer-layout" data-fullbleed data-push data-responsive-width="992px" data-has-scrolling-region>

      <div class="mdk-drawer-layout__content">
        <!-- header-layout -->
        <div class="mdk-header-layout js-mdk-header-layout  mdk-header--fixed  mdk-header-layout__content--scrollable">
          <!-- header -->
          <div class="mdk-header js-mdk-header bg-primary" data-fixed>
              <div class="mdk-header__content">
                <%= render 'layouts/navbar' %>
              </div>
          </div>

          <!-- content -->
          <div class="mdk-header-layout__content top-navbar mdk-header-layout__content--scrollable h-100">
              <!-- main content -->
              
          </div>
        </div>

      </div>
      <!-- // END drawer-layout__content -->

      <!-- drawer -->
      <div class="mdk-drawer js-mdk-drawer" id="default-drawer">
        <div class="mdk-drawer__content">
          <div class="mdk-drawer__inner" data-simplebar data-simplebar-force-enabled="true">
            <%= render 'layouts/sidebar' %>
          </div>
        </div>
      </div>
      <!-- // END drawer -->
    </div>

    <br /><br />
  <%= yield %>  
       
<%= render 'layouts/footer' %>

</body>
</html>